language: android

# installing Java 8 JDK is required to prevent getting "Unsupported major.minor version 52.0" error
jdk:
  - oraclejdk8

# Travis now has Xenial builds as default -> https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
# Though, Android builds are not yet supported on Xenial
dist: trusty

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.0
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses

script:
  - ./gradlew clean check --stacktrace --no-daemon
  - ./gradlew build jacocoTestReport assembleAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo:
  false

notifications:
  email: false